# -*- coding: utf-8 -*-
"""Pandas_File_Read.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Evpf2en0Av79U6EFqR58mef_vIj9WYGp
"""

import pandas as pd

# Load a CSV file into a DataFrame
df = pd.read_csv('students_data.csv')

# Display the first few rows
print(df.head())