# -*- coding: utf-8 -*-
"""Pandas_File_Upload.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Evpf2en0Av79U6EFqR58mef_vIj9WYGp
"""

from google.colab import files

upload = files.upload()