# -*- coding: utf-8 -*-
"""Pandas_Various_Commands.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Evpf2en0Av79U6EFqR58mef_vIj9WYGp
"""

# Load a CSV file into a DataFrame
df = pd.read_csv('students_data.csv')

# Display the first few rows
#print(df.head())

#See DataFrame dimensions
#print(df.shape)

#Get column names and types
#print(df.info())

#Statistical summary
#print(df.describe())

#Detect missing values
#print(df.Name.sum)

#Removing missing data
#df.dropna()

#Filling missing values
#df.fillna(0)